2015/06/25 04:15:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\IM\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\IM\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\IM\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\IM\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\IM\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\IM\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\IM\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\IM\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\IM\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\IM\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\IM\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\IM\login\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/IM/login/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/IM/login/index.php?r=gii/default/index
---
2015/06/25 04:18:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'login'' in C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\IM\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\IM\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\IM\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\IM\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\IM\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\IM\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\IM\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\IM\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\IM\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\IM\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\IM\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\IM\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\IM\login\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/IM/login/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/IM/login/index.php?r=gii/default/index
---
2015/06/25 05:29:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/Admin/create".' in C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/Admin/crea...')
#1 C:\xampp\htdocs\IM\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\IM\login\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/IM/login/index.php?r=user/Admin/create
HTTP_REFERER=http://localhost/IM/login/index.php?r=site/login
---
2015/06/25 05:32:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TblUserAdminController/create".' in C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\IM\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblUserAdminCon...')
#1 C:\xampp\htdocs\IM\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\IM\login\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/IM/login/index.php?r=TblUserAdminController/create
HTTP_REFERER=http://localhost/IM/login/index.php?r=site/login
---
2015/06/25 09:57:56 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'login.a' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `a`.
in C:\xampp\htdocs\IM\login\index.php (13)
